openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/customers/upload":
    post:
      summary: Upload customer file
      tags:
        - Customers
      requestBody:
        required: true
        description: Customers file (JSON lines format)
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                customers_file:
                  type: string
                  format: binary
      responses:
        "200":
          description: customers filtered
        "400":
          description: file missing
servers:
  - url: http://localhost:3000